name: Build with Maven and SonarCloud scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build for push
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
        if: ${{ github.event_name == 'push' }}

      - name: Build for pull request
        run: mvn verify -Dmaven.test.redirectTestOutputToFile=false -B -e -V
        if: ${{ github.event_name == 'pull_request' }}
